apiVersion: v2
name: opentelemetry-collector
<<<<<<< HEAD
version: 0.37.0
=======
version: 0.35.1
>>>>>>> 2e7d946 ([opentelemetry-collector] add kubernetes attributes processor)
description: OpenTelemetry Collector Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: dmitryax
  - name: TylerHelmuth
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 0.62.1
